swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /vote:
    x-swagger-router-controller: voting
    post:
      tags: 
        - vote
      summary: Register a vote for a movie
      operationId: vote
      parameters:
        - in: body
          name: voteRequest
          description: The movie id and email
          required: true
          schema:
            $ref: '#/definitions/VoteRequest'
      responses:
        200:
          description: Ok
          schema:
            type: string
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  VoteRequest:
      properties:
        movieId:
          type: string
        userEmail:
          type: string
          format: email
  VoteResponse:
    type: string
